/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_dbyz_java_jni_FirstJniTest */

#ifndef _Included_org_dbyz_java_jni_FirstJniTest
#define _Included_org_dbyz_java_jni_FirstJniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_dbyz_java_jni_FirstJniTest
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
 /*此处方法名以_开头*/
JNIEXPORT jstring JNICALL _Java_org_dbyz_java_jni_FirstJniTest_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
